/*
 * generated by Xtext
 */
package org.xtext

/** 
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
class CommonlangStandaloneSetup extends CommonlangStandaloneSetupGenerated {
	def static void doSetup() {
		new CommonlangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
