/*
 * generated by Xtext
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.services.CommonlangGrammarAccess;

@SuppressWarnings("all")
public class CommonlangSyntacticSequencer extends AbstractSyntacticSequencer {

	protected CommonlangGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Call_CommaKeyword_3_0_p;
	protected AbstractElementAlias match_MetaMethod_CommaKeyword_5_0_p;
	protected AbstractElementAlias match_UserMethod_CommaKeyword_4_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (CommonlangGrammarAccess) access;
		match_Call_CommaKeyword_3_0_p = new TokenAlias(true, false, grammarAccess.getCallAccess().getCommaKeyword_3_0());
		match_MetaMethod_CommaKeyword_5_0_p = new TokenAlias(true, false, grammarAccess.getMetaMethodAccess().getCommaKeyword_5_0());
		match_UserMethod_CommaKeyword_4_0_p = new TokenAlias(true, false, grammarAccess.getUserMethodAccess().getCommaKeyword_4_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Call_CommaKeyword_3_0_p.equals(syntax))
				emit_Call_CommaKeyword_3_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_MetaMethod_CommaKeyword_5_0_p.equals(syntax))
				emit_MetaMethod_CommaKeyword_5_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_UserMethod_CommaKeyword_4_0_p.equals(syntax))
				emit_UserMethod_CommaKeyword_4_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','+
	 *
	 * This ambiguous syntax occurs at:
	 *     method=[Method|CAPITALFIRST] '(' (ambiguity) parameters+=Value
	 *     method=[Method|LOWERFIRST] '(' (ambiguity) parameters+=Value
	 *     parameters+=Value (ambiguity) parameters+=Value
	 */
	protected void emit_Call_CommaKeyword_3_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','+
	 *
	 * This ambiguous syntax occurs at:
	 *     name=CAPITALFIRST '(' (ambiguity) parameters+=Declaration
	 *     parameters+=Declaration (ambiguity) parameters+=Declaration
	 */
	protected void emit_MetaMethod_CommaKeyword_5_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','+
	 *
	 * This ambiguous syntax occurs at:
	 *     name=LOWERFIRST '(' (ambiguity) parameters+=Declaration
	 *     parameters+=Declaration (ambiguity) parameters+=Declaration
	 */
	protected void emit_UserMethod_CommaKeyword_4_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
