/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CommonlangUiModule extends org.xtext.ui.AbstractCommonlangUiModule {
	public CommonlangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
